steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/redirector', '.']
images: ['eu.gcr.io/$PROJECT_ID/redirector']
