steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=redirector', 'CGO_ENABLED=0']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/redirector', '.']
images: ['eu.gcr.io/$PROJECT_ID/redirector']
