apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redirector
  labels:
    app: redirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirector
  template:
    metadata:
      labels:
        app: redirector
    spec:
      containers:
      - name: redirector
        image: eu.gcr.io/gordonmleighuk/redirector:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: redirector
  labels:
    app: redirector
spec:
  ports:
  - port: 4000
    protocol: TCP
  selector:
    app: redirector